### ISSUE TITLE
Error in vstemplate file

### ISSUE THREAD

**Issue by peterloudon** [MscrmTools/XrmToolBoxPluginTemplate#2]
When trying to create a project from the latest version of the template the following error is generated:

_Microsoft Visual Studio Package Installation Error The project template lists one or more packages with missing, empty, or invalid values for the id or version attributes. Both attributes are required and must have valid values._ 

The cause seems to be in the following line of the vstemplate file:

"package id="Microsoft.CrmSdk.CoreAssemblies" version="9.0.2.1e" targetFramework="net462" /"

The version should be "9.0.2.12"

**Comment by MscrmTools** [comment]
Thanks! it's now fixed
